# -*- coding: utf-8 -*-
"""Language_Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/KhanakhP/Language_Detection/blob/main/Language_Detection.ipynb

Language Detection Model
"""

import re
import warnings
warnings.simplefilter("ignore")

import pandas as pd
import numpy as np

import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv("Language Detection.csv")
df.head()

df.shape

df["Language"].value_counts()

X = df["Text"]
y = df["Language"]

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

y

text_list = []

for text in X:
        text = re.sub(r'[!@#$(),n"%^*?:;~`0-9]', ' ', text)
        text = re.sub(r'[[]]', ' ', text)
        text = text.lower()
        text_list.append(text)

from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
X = cv.fit_transform(text_list).toarray()
X.shape

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)

from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(x_train, y_train)

y_prediction = model.predict(x_test)

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

accuracy = accuracy_score(y_test, y_prediction)
confusion_m = confusion_matrix(y_test, y_prediction)

print("The accuracy is :",accuracy)

plt.figure(figsize=(15,10))
sns.heatmap(confusion_m, annot = True)
plt.show()

def lang_predict(text):
     x = cv.transform([text]).toarray()
     lang = model.predict(x)
     lang = le.inverse_transform(lang)
     print("The langauge is in",lang[0])

lang_predict("Today is going to be very busy because I have a lot of things to do.")

lang_predict("سيكون اليوم مشغولاً للغاية لأن لدي الكثير من الأشياء لأفعلها.")

lang_predict("आज का दिन बहुत व्यस्त रहने वाला है क्योंकि मेरे पास करने के लिए बहुत कुछ है।")

lang_predict("Сегодня будет очень занят, потому что у меня много дел.")

lang_predict("ഹലോ സുപ്രഭാതം")



